workers_dev = false
preview_urls = false
send_metrics = false
name = "elliotjreed"
compatibility_date = "2025-04-20"
main = "./build/server/index.js"
upload_source_maps = false

[build]
command = "bun run build"

[assets]
directory = "./build/client/"

[observability.logs]
enabled = true

[vars]
